services:

  db:
    container_name: worksafe-postgres
    image: postgres:15-alpine
    restart: always

    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: worksafe
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data: